Repository gpslab/geoip2, pull requests merged in 2020-01, with the labels that each got.

#18 Add info about changed policy and steps for migration
  README.md
Labels: bug

#20 Add "roave/security-advisories" as a firewall for vulnerable components
  composer.json
Labels: feature

#21 Apply fixes from StyleCI
  src/Composer/ScriptHandler.php
Labels: bug

#24 Remove gpslab/compressor
  UPGRADE-2.0.md
  composer.json
  src/Command/UpdateDatabaseCommand.php
  src/Resources/config/services.yml
Labels: feature

#23 Break PHP 5.4 and 7.0
  .travis.yml
  composer.json
  src/Command/UpdateDatabaseCommand.php
  src/Composer/ScriptHandler.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/GpsLabGeoIP2Extension.php
  src/GpsLabGeoIP2Bundle.php
  tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
  tests/GpsLabGeoIP2BundleTest.php
Labels: feature

#25 Not use Stopwatch
  UPGRADE-2.0.md
  composer.json
  src/Command/UpdateDatabaseCommand.php
  src/Resources/config/services.yml
Labels: feature

#27 Сomposer is not used anymore
  composer.json
Labels: bug

#22 Use phar of Scrutinizer CI and PHP Coveralls
  .travis.yml
  composer.json
  phpunit.xml.dist
Labels: feature

#15 Allow Symfony 5
  .travis.yml
  composer.json
Labels: bug

#28 Declare strict types
  .styleci.yml
  src/Command/UpdateDatabaseCommand.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/GpsLabGeoIP2Extension.php
  src/GpsLabGeoIP2Bundle.php
  tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
  tests/GpsLabGeoIP2BundleTest.php
  tests/bootstrap.php
Labels: feature

#29 Configure PHP CS Fixer
  .gitignore
  .php_cs.dist
  src/Command/UpdateDatabaseCommand.php
  src/DependencyInjection/GpsLabGeoIP2Extension.php
  tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
  tests/GpsLabGeoIP2BundleTest.php
Labels: feature

#30 Require PHPStan for Static Analysis PHP
  .php_cs.dist
  composer.json
  phpstan.neon.dist
  src/Command/UpdateDatabaseCommand.php
  src/DependencyInjection/GpsLabGeoIP2Extension.php
  tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
  tests/GpsLabGeoIP2BundleTest.php
Labels: feature

#31 Allow use multi databases
  README.md
  UPGRADE-2.0.md
  composer.json
  phpstan.neon.dist
  src/Command/DownloadDatabaseCommand.php
  src/Command/UpdateDatabaseCommand.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/GpsLabGeoIP2Extension.php
  src/Downloader/Downloader.php
  src/Downloader/MaxMindDownloader.php
  src/Reader/ReaderFactory.php
  src/Resources/config/services.yml
  tests/Command/DownloadDatabaseCommandTest.php
  tests/Command/UpdateDatabaseCommandTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/GpsLabGeoIP2ExtensionTest.php
  tests/Downloader/MaxMindDownloaderTest.php
  tests/GpsLabGeoIP2BundleTest.php
  tests/Reader/ReaderFactoryTest.php
  tests/Reader/TestReader.php
Labels: BC break, feature

#32 Not use ArrayNodeDefinition::cannotBeEmpty()
  src/DependencyInjection/Configuration.php
Labels: bug
